
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2008.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2009.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2010.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2011.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2012.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2013.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2014.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2015.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2016.xls"

python createTimeSeries.py
