
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2000.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2001.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2002.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2003.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2004.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2005.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2006.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2007.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2008.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2009.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2010.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2011.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2012.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2013.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2014.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2015.xls"
python migration.py "underlyingdatasheet4.01ipscitizenshipgroupbysexbyagebycountryoflastornextresidence2016.xls"

python createTimeSeries.py

